name: npm package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: npm package
    permissions:
      id-token: write # Required for OIDC
      contents: read # Required for actions/checkout
      attestations: write # Required for attestation
      packages: write # Required for publishing to github packages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Test package
        run: bun test

      - name: Build package
        run: bun run build

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Publish to npm
        run: npm publish --provenance --access public ./dist

      - name: Publish to GitHub Packages
        run: npm publish --provenance --access public --registry https://npm.pkg.github.com ./dist
